import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import request from 'supertest';
import { AppModule } from '../../src/app.module'; 

describe('ColumnsController (e2e)', () => {
  let app: INestApplication;

  beforeEach(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();
  });

  it('/boards/:boardId/columns/ (POST)', async () => {
    const response = await request(app.getHttpServer())
      .post('/boards/1/columns/')  
      .set('Authorization', 'Bearer ')  

    expect(response.status).toBe(200);
    expect(response.body.message).toBe('컬럼 자동 생성에 성공했습니다.');
    expect(response.body.autoGeneratedColumn).toBeDefined();
  });

  afterAll(async () => {
    await app.close();
  });
});
